ccflags-y += -Idrivers/media/platform/msm/camera_v2_A6020
ccflags-y += -Idrivers/media/platform/msm/camera_v2_A6020/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_A6020/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
