ccflags-y += -Idrivers/media/platform/msm/camera_v2_A6020
ccflags-y += -Idrivers/media/platform/msm/camera_v2_A6020/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_A6020/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_ois.o
